### ISSUE TITLE
[Bug] Failed to normalize file name FRON

### ISSUE THREAD

**Issue by Diomedes56** [suXinjke/VengeanceRipper#2]
Hello.

I am french, sorry for my bad english.

In wantig to extract the file GAME.RSC of Colony Wars : Vengeance for make a revival with Godot Engine, the terminal display me an serie of errors.

node game_rsc_extract.js /home/manjaro/Bureau/Colony_Wars_1/CW1_CD1/GAME.RSC /home/manjaro/Bureau/Colony_Wars_1/CW1_CD1/GAME-RSC_js/
Error: Failed to normalize file name FRON
    at parseFiles (/home/manjaro/Téléchargements/VengeanceRipper-master/game_rsc_extract.js:18:19)
    at main (/home/manjaro/Téléchargements/VengeanceRipper-master/game_rsc_extract.js:61:19)
    at async /home/manjaro/Téléchargements/VengeanceRipper-master/game_rsc_extract.js:74:9

My software configuration is:
Manjaro XFCE 21.1.0-210817 64 bits in Virtualbox.
NodeJS 16.7.0-1 with Jimp via the command "node install jimp".

My Javascript skills being null, i not can help you, but after have used RedSunRipper for Colony Wars : Red Sun GAME.RSC file, i found a file with a similar name named FRONT.OVL, this may a file of this type.

Cordially.
Gallonigher.

**Comment by suXinjke** [comment]
> Colony_Wars_1/CW1_CD1

Does this imply you try to use the ripper on original Colony Wars? I never tested neither planned to deal with original game, only Vengeance

**Comment by Diomedes56** [comment]
Hello.

Sorry for writing nonsense, I forgot a nice piece in my text editor, probably tired from last night.

I wanted to say that it worked well with Colony Wars: Vengeance for my project with Godot Engine but not with Colony Wars 1 whereas RedSun Ripper works well with the game of the same name and moreover, it creates the directories, which is not the case with VengeanceRipper.

I will test model_converter.js.

All Playstation 1 binaries are extracted with PSXImager:
https://github.com/cebix/psximager

Traduction by DeepL.

Cordially.

**Comment by suXinjke** [comment]
So what is the actual issue? Lack of directories? Vengeance has no directories

Or you're asking for Colony Wars 1 ripping

**Comment by Diomedes56** [comment]
> So what is the actual issue? Lack of directories? Vengeance has no directories
Ha, i dont know that the GAME.RSC archive of Colony Wars Vengeance dont have subfolder.

The Colony Wars : Vengeance resources you extracted (found on The Models Resource) are not to scale, which is why I want to extract them from my PAL game for comparison.

Example:
The Navy Hex has a length of 13,400 m
The Navy Frigate has a length of 18 368 m
Proportions not corresponding to the set.

So this topic has no reason to exist, however, model_converter.js tells me that jimp is not installed when it is.




> Or you're asking for Colony Wars 1 ripping

I would have been interested but I doubt it would be relevant at the moment, here are the reasons:
- I am concentrating on Colony Wars Vengeance and my visual impairment is slowing me down.
- I just discovered your website and you do a huge and admirable job of reverse engineering which must take up a lot of your free time.
- There are works on that allowed me to extract some content like PSXimager and JPSXdec ( https://github.com/m35/jpsxdec ).

Translated with www.DeepL.com/Translator (free version)
